### ISSUE TITLE
update fsdb dependency to v0.3

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#132]
follow the [changelog](https://github.com/ael-code/pyFsdb/releases) to update code.

**Comment by boyska** [comment]
In doing this, I'd like to move some code in LibreantCoreApp, starting the slow process of making the webapp a bit tidier. I'd try to be as flask-agnostic as possible.

Doing this we can also have unit tests about the web application logic.

**Comment by boyska** [comment]
I'm doing this right now

**Comment by boyska** [comment]
@ael-code can you give a read at https://github.com/boyska/libreant/tree/132-libreant-logic-fsdb please?
I'd like your opinion on this refactoring.

I know that you really don't like moving things into LibreantCoreApp, which is a subclass of Flask, but I am trying hard not to rely too much on flask, so that it will be easier to move to something more agnostic, once we have a good design of it.

By now, the only part that is flask-aware (but does _not_ rely on flask) is the mimetype and filename attributes of `upFile`. If those attributes do not exist, there will be no mimetype info, but still no errors!

**Comment by leophys** [comment]
Closed via #133
