### ISSUE TITLE
cli errors handling

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#230]
The `libreant` command behaves strangely on some error handling situation.
In particular I noticed:
 - if an error is raised in debug mode the porgram does not terminate. For example using an unauthorized port `libreant -d -p 1` the program will print the stack trace but it won't exit.
 - if an error is raised in non-debug mode the program will terminate with exit code 0. Also here you can reproduce the scenario with `libreant -p 1`

**Comment by boyska** [comment]
> - if an error is raised in debug mode the porgram does not terminate.
>   For example using an unauthorized port `libreant -d -p 1` the
>   program will print the stack trace but it won't exit.

I think that this is about the reloader.
We could split debug and reloader if we feel so.

**Comment by ael-code** [comment]
> I think that this is about the reloader. We could split debug and reloader if we feel so.

Yes is about the reloader. Bypassing it, the error won't be even printed.

Anyway looking at Werkzeug code[1] seems that we are using the wrong function. We should move to `run_simple` and use the params to set the reloader correctly.


[1] https://github.com/mitsuhiko/werkzeug/blob/master/werkzeug/serving.py#L695

**Comment by ael-code** [comment]
The code in `webant/webserver_utils.py` is messed up.
What about using gevent in normal mode and the werkzeug `run_simple` WSGI server implementation for debugging mode.

**Comment by boyska** [comment]
>What about using gevent in normal mode and the werkzeug `run_simple`
>WSGI server implementation for debugging mode.

<troll> http://12factor.net/dev-prod-parity </troll>

I don't like much making development and production different, it makes
code harder and bugs less detectable.
Specifically, gevent was introduced because the simple wsgi server
cannot handle requests concurrently, which is required for agherant.
Yes, agherant state is sad, so this is a non-issue now. Still, I'd like
to have a general purpose solutions. If it implies that we must drop
reloader, this is not an issue for me (never liked it too much).
